### ISSUE TITLE
'InsideOut.pm line 1953 during global destruction' error running genemark-ES

### ISSUE THREAD

**Issue by drelo** [patrickwest/EukRep_Pipeline#3]
Dear Patrick

I used CONCOT to obtain the bins during this pipeline and now I had a problem using GeneMark-ES. I reduced the '_min_contig_' to try with my dataset and I edited the _gmes.cfg_ file accordingly using  `min_contig:    2500` . Following the advice in [another github issue](https://github.com/nextgenusfs/funannotate/issues/242) I run  `change_path_in_perl_scripts.pl` with my perl executable in my conda environment, I also installed `cpanm Hash::Merge` and that seemed to fix a previous error. Now  I run `perl  ../gmes_linux_64/gmes_petap.pl  --ES -min_contig 2500 --sequence 14.fa` 

This is the last part of the output of this stage:

```
Intergenic:	130	25510
SvsM  0.121518987341772 vs 0.878481012658228
genes in IvsT all and selected: 1260 330
1, -1.56498614986327
2, -1.57958494928442
3, -1.44238382777093
4, -2.11021320034659
5, -2.03789253876696
6, -3.09104245335832
7, -2.96587931040431
# estimate 1: 0.721428571428571
# estimate 2: 0.75629398124262
# value: 0.75629398124262
IvsT  0.75629398124262 vs 0.24370601875738
	(in cleanup) 	(in cleanup)  at /mnt/ubi/andres/miniconda3/envs/eukarya/lib/site_perl/5.26.2/Object/InsideOut.pm line 1953 during global destruction.
(eukarya) [andrespara@nagual clusters]$ vim /mnt/ubi/andres/miniconda3/envs/eukarya/lib/site_perl/5.26.2/Object/InsideOut.pm
```
Please find attached a file of one of the bins.
[16.fa.txt](https://github.com/patrickwest/EukRep_Pipeline/files/5313571/16.fa.txt)

This is the length of the sequences inside the file (I already filtered those <2500)

NODE_423_length_9247_cov_24.787859	9247
NODE_4198_length_2911_cov_22.738796	2911

Do you know how to fix this? Thanks for your help.

**Comment by Jiangjiangzhang6** [comment]
Dear my friend, how did you solve this err, I met the same bug,

**Comment by drelo** [comment]
I couldn't fix it and the lab moved onto analyzing another dataset instead. Sorry
